require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Product = require('../models/Product');
const User = require('../models/User');

const products = [
  // Electronics - Laptops
  { name: 'Apple MacBook Air M2', description: 'The latest MacBook Air with the powerful M2 chip. Features a stunning Liquid Retina display, all-day battery life, and a silent fanless design. Perfect for professionals and students alike.', shortDescription: 'Apple M2 chip, 8GB RAM, 256GB SSD, 13.6" Liquid Retina', price: 114900, originalPrice: 129900, images: [{ url: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=500', alt: 'MacBook Air M2' }], category: 'Laptops', subcategory: 'Ultrabooks', brand: 'Apple', stock: 25, sku: 'APPLE-MBA-M2-8-256', specifications: [{ key: 'Processor', value: 'Apple M2' }, { key: 'RAM', value: '8GB Unified Memory' }, { key: 'Storage', value: '256GB SSD' }, { key: 'Display', value: '13.6" Liquid Retina' }, { key: 'Battery', value: 'Up to 18 hours' }], tags: ['apple', 'macbook', 'laptop', 'ultrabook', 'm2', 'macos'], ratings: 4.8, numReviews: 342, isFeatured: true, purchaseCount: 1240 },
  { name: 'Dell XPS 15 OLED', description: 'Premium 15-inch laptop with InfinityEdge OLED display. Powered by Intel Core i7 13th Gen with NVIDIA RTX 4060. Perfect for creative professionals and power users.', shortDescription: 'Intel i7-13700H, 16GB DDR5, 512GB SSD, 15.6" OLED 3.5K', price: 149990, originalPrice: 179990, images: [{ url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=500', alt: 'Dell XPS 15' }], category: 'Laptops', subcategory: 'Premium Laptops', brand: 'Dell', stock: 18, sku: 'DELL-XPS15-OLED-I7', specifications: [{ key: 'Processor', value: 'Intel Core i7-13700H' }, { key: 'RAM', value: '16GB DDR5' }, { key: 'Storage', value: '512GB NVMe SSD' }, { key: 'Display', value: '15.6" 3.5K OLED' }, { key: 'GPU', value: 'NVIDIA RTX 4060' }], tags: ['dell', 'xps', 'oled', 'gaming', 'laptop', 'creator'], ratings: 4.6, numReviews: 187, isFeatured: true, purchaseCount: 890 },
  { name: 'Lenovo IdeaPad Slim 5', description: 'Stylish and powerful laptop for everyday computing. AMD Ryzen 5 processor with fast SSD storage and long battery life. Great value for money.', shortDescription: 'AMD Ryzen 5 7530U, 16GB RAM, 512GB SSD, 14" FHD', price: 54990, originalPrice: 69990, images: [{ url: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500', alt: 'Lenovo IdeaPad' }], category: 'Laptops', subcategory: 'Everyday Laptops', brand: 'Lenovo', stock: 45, sku: 'LENOVO-IPS5-R5-16', specifications: [{ key: 'Processor', value: 'AMD Ryzen 5 7530U' }, { key: 'RAM', value: '16GB DDR4' }, { key: 'Storage', value: '512GB SSD' }, { key: 'Display', value: '14" FHD IPS' }], tags: ['lenovo', 'ideapad', 'amd', 'student', 'laptop'], ratings: 4.3, numReviews: 524, purchaseCount: 2100 },
  { name: 'ASUS ROG Strix G16', description: 'Dominate every game with the ROG Strix G16 gaming laptop. Equipped with RTX 4070 and 240Hz display for the smoothest gaming experience.', shortDescription: 'Intel i9-13980HX, 32GB DDR5, 1TB SSD, RTX 4070, 240Hz', price: 184990, originalPrice: 209990, images: [{ url: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500', alt: 'ASUS ROG Gaming Laptop' }], category: 'Laptops', subcategory: 'Gaming Laptops', brand: 'ASUS', stock: 12, sku: 'ASUS-ROG-G16-I9-RTX4070', specifications: [{ key: 'Processor', value: 'Intel Core i9-13980HX' }, { key: 'RAM', value: '32GB DDR5' }, { key: 'Storage', value: '1TB NVMe SSD' }, { key: 'GPU', value: 'NVIDIA RTX 4070' }, { key: 'Display', value: '16" FHD 240Hz' }], tags: ['asus', 'rog', 'gaming', 'laptop', 'rtx', 'high-performance'], ratings: 4.7, numReviews: 298, isFeatured: true, purchaseCount: 745 },
  { name: 'HP Pavilion 15', description: 'A reliable everyday laptop with Intel Core i5 and 8GB RAM. Great for office work, browsing, and light entertainment.', shortDescription: 'Intel Core i5-1235U, 8GB RAM, 512GB SSD, 15.6" FHD', price: 47990, originalPrice: 59990, images: [{ url: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500', alt: 'HP Pavilion' }], category: 'Laptops', subcategory: 'Everyday Laptops', brand: 'HP', stock: 60, sku: 'HP-PAV15-I5-8-512', specifications: [{ key: 'Processor', value: 'Intel Core i5-1235U' }, { key: 'RAM', value: '8GB DDR4' }, { key: 'Storage', value: '512GB SSD' }], tags: ['hp', 'pavilion', 'intel', 'student', 'office', 'laptop'], ratings: 4.1, numReviews: 892, purchaseCount: 3200 },

  // Electronics - Phones
  { name: 'Apple iPhone 15 Pro', description: 'The most advanced iPhone ever with the A17 Pro chip, titanium design, and the all-new Action Button. Features a 48MP main camera with 5x optical zoom.', shortDescription: 'A17 Pro chip, 256GB, 48MP ProCamera, USB-C, 6.1"', price: 134900, originalPrice: 149900, images: [{ url: 'https://images.unsplash.com/photo-1697299880390-8e40b0e93beb?w=500', alt: 'iPhone 15 Pro' }], category: 'Smartphones', subcategory: 'Premium Phones', brand: 'Apple', stock: 50, sku: 'APPLE-IP15PRO-256', specifications: [{ key: 'Chip', value: 'A17 Pro' }, { key: 'Storage', value: '256GB' }, { key: 'Camera', value: '48MP + 12MP + 12MP' }, { key: 'Display', value: '6.1" Super Retina XDR ProMotion' }, { key: 'Battery', value: '3274 mAh' }], tags: ['apple', 'iphone', 'ios', 'premium', 'smartphone', 'pro'], ratings: 4.9, numReviews: 1205, isFeatured: true, purchaseCount: 4500 },
  { name: 'Samsung Galaxy S24 Ultra', description: 'The ultimate Galaxy experience with the built-in S Pen, 200MP camera, and Snapdragon 8 Gen 3. AI-powered features for productivity and creativity.', shortDescription: 'Snapdragon 8 Gen 3, 12GB RAM, 256GB, 200MP, S Pen', price: 129999, originalPrice: 149999, images: [{ url: 'https://images.unsplash.com/photo-1706700399571-6a6e74fa5bfe?w=500', alt: 'Samsung S24 Ultra' }], category: 'Smartphones', subcategory: 'Premium Phones', brand: 'Samsung', stock: 35, sku: 'SAM-S24U-12-256', specifications: [{ key: 'Processor', value: 'Snapdragon 8 Gen 3' }, { key: 'RAM', value: '12GB' }, { key: 'Storage', value: '256GB' }, { key: 'Camera', value: '200MP + 50MP + 12MP + 10MP' }, { key: 'Display', value: '6.8" QHD+ Dynamic AMOLED 120Hz' }], tags: ['samsung', 'galaxy', 's24', 'ultra', 'android', 'flagship', 's-pen'], ratings: 4.8, numReviews: 876, isFeatured: true, purchaseCount: 3800 },
  { name: 'OnePlus 12R', description: 'Flagship killer with Snapdragon 8 Gen 1, 50MP triple camera, and 100W SUPERVOOC charging. The perfect balance of performance and price.', shortDescription: 'Snapdragon 8 Gen 1, 8GB RAM, 128GB, 50MP, 100W Charging', price: 39999, originalPrice: 44999, images: [{ url: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500', alt: 'OnePlus 12R' }], category: 'Smartphones', subcategory: 'Mid-Range', brand: 'OnePlus', stock: 80, sku: 'OP-12R-8-128', specifications: [{ key: 'Processor', value: 'Snapdragon 8 Gen 1' }, { key: 'RAM', value: '8GB LPDDR5' }, { key: 'Storage', value: '128GB UFS 3.1' }, { key: 'Camera', value: '50MP + 8MP + 2MP' }, { key: 'Charging', value: '100W SUPERVOOC' }], tags: ['oneplus', 'android', 'flagship-killer', 'fast-charging', 'smartphone'], ratings: 4.5, numReviews: 2100, purchaseCount: 7800 },
  { name: 'Xiaomi 14 Ultra', description: 'Co-engineered with Leica for pro-grade photography. Features a 1-inch Sony sensor, Snapdragon 8 Gen 3, and 90W HyperCharge.', shortDescription: 'Snapdragon 8 Gen 3, 16GB RAM, 512GB, Leica 50MP, 90W', price: 99999, originalPrice: 109999, images: [{ url: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=500', alt: 'Xiaomi 14 Ultra' }], category: 'Smartphones', subcategory: 'Premium Phones', brand: 'Xiaomi', stock: 20, sku: 'MI-14U-16-512', specifications: [{ key: 'Processor', value: 'Snapdragon 8 Gen 3' }, { key: 'RAM', value: '16GB LPDDR5X' }, { key: 'Storage', value: '512GB UFS 4.0' }, { key: 'Camera', value: '50MP Leica (1-inch) + 50MP + 50MP + 50MP' }], tags: ['xiaomi', 'leica', 'camera', 'flagship', 'smartphone', 'pro'], ratings: 4.7, numReviews: 456, purchaseCount: 2100 },
  { name: 'Realme Narzo 60x', description: 'Great budget phone with a 50MP AI camera, 5000mAh battery, and Dimensity 6100+ processor. Best for value seekers.', shortDescription: 'Dimensity 6100+, 6GB RAM, 128GB, 50MP Camera, 5000mAh', price: 12999, originalPrice: 15999, images: [{ url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500', alt: 'Realme Narzo 60x' }], category: 'Smartphones', subcategory: 'Budget Phones', brand: 'Realme', stock: 120, sku: 'RM-NARZO60X-6-128', specifications: [{ key: 'Processor', value: 'Dimensity 6100+' }, { key: 'RAM', value: '6GB' }, { key: 'Storage', value: '128GB' }, { key: 'Battery', value: '5000mAh + 33W charging' }], tags: ['realme', 'budget', 'android', 'battery', 'smartphone'], ratings: 4.0, numReviews: 3400, purchaseCount: 12000 },

  // Audio
  { name: 'Sony WH-1000XM5', description: 'Industry-leading noise canceling headphones with crystal clear hands-free calling and up to 30 hours battery life. New Auto NC Optimizer for any environment.', shortDescription: 'Industry-best ANC, 30hr battery, multipoint connect, Bluetooth 5.2', price: 26990, originalPrice: 34990, images: [{ url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500', alt: 'Sony WH-1000XM5' }], category: 'Headphones', subcategory: 'Over-Ear', brand: 'Sony', stock: 40, sku: 'SONY-WH1000XM5-BLK', specifications: [{ key: 'ANC', value: '8 microphones, Auto NC Optimizer' }, { key: 'Battery', value: '30 hours (ANC on)' }, { key: 'Bluetooth', value: '5.2 with Multipoint' }, { key: 'Driver', value: '30mm' }], tags: ['sony', 'headphones', 'anc', 'wireless', 'noise-cancelling', 'premium'], ratings: 4.8, numReviews: 756, isFeatured: true, purchaseCount: 3200 },
  { name: 'boAt Airdopes 141', description: 'True wireless earbuds with ENx technology for clear calls, 42 hours total playback with case, and IPX4 water resistance. Best value TWS.', shortDescription: 'ENx Call Tech, 42H playtime, BEAST Mode, IPX4', price: 1299, originalPrice: 4490, images: [{ url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500', alt: 'boAt Airdopes 141' }], category: 'Headphones', subcategory: 'TWS Earbuds', brand: 'boAt', stock: 200, sku: 'BOAT-AIRP141-BLU', specifications: [{ key: 'Battery', value: '6H + 36H (case)' }, { key: 'Latency', value: '50ms Gaming Mode' }, { key: 'Water Resistance', value: 'IPX4' }], tags: ['boat', 'earbuds', 'tws', 'wireless', 'budget', 'gaming'], ratings: 4.1, numReviews: 8900, purchaseCount: 45000 },
  { name: 'JBL Tune 770NC', description: 'Adaptive Noise Cancelling with 4 mics. Up to 70 hours of battery. Smart Ambient mode. Foldable design for portability.', shortDescription: 'Adaptive ANC, 70hr battery, Bluetooth 5.3, foldable', price: 6999, originalPrice: 12999, images: [{ url: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500', alt: 'JBL Tune 770NC' }], category: 'Headphones', subcategory: 'Over-Ear', brand: 'JBL', stock: 65, sku: 'JBL-T770NC-BLK', specifications: [{ key: 'ANC', value: 'Adaptive with 4 mics' }, { key: 'Battery', value: '70 hours' }, { key: 'Bluetooth', value: '5.3' }], tags: ['jbl', 'headphones', 'anc', 'wireless', 'foldable'], ratings: 4.4, numReviews: 1230, purchaseCount: 5600 },

  // TVs
  { name: 'Samsung 55" QLED 4K Smart TV', description: 'Experience stunning picture quality with Quantum Dot technology, 100% Color Volume, and Quantum HDR. Smart TV with built-in Alexa and Google Assistant.', shortDescription: '4K QLED, 120Hz, Quantum HDR, Tizen OS, Alexa Built-in, 55"', price: 59990, originalPrice: 89990, images: [{ url: 'https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=500', alt: 'Samsung QLED TV' }], category: 'Televisions', subcategory: 'QLED', brand: 'Samsung', stock: 15, sku: 'SAM-55Q70C-QLED', specifications: [{ key: 'Screen Size', value: '55 inches' }, { key: 'Resolution', value: '4K UHD (3840x2160)' }, { key: 'Panel', value: 'QLED' }, { key: 'Refresh Rate', value: '120Hz' }, { key: 'OS', value: 'Tizen' }], tags: ['samsung', 'tv', 'qled', '4k', 'smart-tv', '55inch'], ratings: 4.6, numReviews: 432, isFeatured: true, purchaseCount: 1890 },
  { name: 'LG 43" 4K IPS LED Smart TV', description: 'LG 4K TV with IPS panel for wide viewing angles, webOS 23, and AI ThinQ for smart home integration. Great for family viewing.', shortDescription: '4K IPS, webOS 23, AI ThinQ, Dolby Vision, 43"', price: 34990, originalPrice: 44990, images: [{ url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=500', alt: 'LG 4K TV' }], category: 'Televisions', subcategory: 'LED Smart TV', brand: 'LG', stock: 30, sku: 'LG-43UR7500-4K', specifications: [{ key: 'Screen Size', value: '43 inches' }, { key: 'Resolution', value: '4K UHD' }, { key: 'Panel', value: 'IPS LED' }, { key: 'OS', value: 'webOS 23' }], tags: ['lg', 'tv', '4k', 'smart-tv', 'ips', '43inch'], ratings: 4.4, numReviews: 678, purchaseCount: 3100 },

  // Cameras
  { name: 'Sony Alpha A7IV Full-Frame Mirrorless', description: 'Professional-grade full-frame mirrorless camera with 33MP BSI-CMOS sensor, 4K 60p video, and 759 phase-detect AF points. The complete camera for pros.', shortDescription: '33MP Full-Frame, 4K60p, 759 AF points, 10fps burst, IBIS', price: 239990, originalPrice: 269990, images: [{ url: 'https://images.unsplash.com/photo-1606986628423-3c6e2e0f53a0?w=500', alt: 'Sony A7IV' }], category: 'Cameras', subcategory: 'Mirrorless', brand: 'Sony', stock: 8, sku: 'SONY-A7IV-BODY', specifications: [{ key: 'Sensor', value: '33MP Full-Frame BSI-CMOS' }, { key: 'Video', value: '4K 60p 10-bit' }, { key: 'AF Points', value: '759 phase-detect' }, { key: 'ISO', value: '100-51200' }], tags: ['sony', 'camera', 'mirrorless', 'full-frame', 'professional', 'video'], ratings: 4.9, numReviews: 167, purchaseCount: 340 },
  { name: 'Canon EOS R50 Mirrorless Camera', description: 'Compact and lightweight mirrorless camera for creators. Features 24.2MP APS-C sensor, 4K video, and powerful Dual Pixel CMOS AF II. Perfect for vlogging.', shortDescription: '24.2MP APS-C, 4K video, Dual Pixel AF II, Flip touchscreen', price: 74990, originalPrice: 89990, images: [{ url: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=500', alt: 'Canon EOS R50' }], category: 'Cameras', subcategory: 'Mirrorless', brand: 'Canon', stock: 22, sku: 'CANON-R50-BODY', specifications: [{ key: 'Sensor', value: '24.2MP APS-C CMOS' }, { key: 'Video', value: '4K UHD 30p' }, { key: 'AF', value: 'Dual Pixel CMOS AF II' }], tags: ['canon', 'camera', 'mirrorless', 'vlogging', 'content-creator', 'aps-c'], ratings: 4.6, numReviews: 289, purchaseCount: 1200 },

  // Tablets
  { name: 'Apple iPad Pro 12.9" M2', description: 'The ultimate iPad with the M2 chip, Liquid Retina XDR display with ProMotion, and support for Apple Pencil hover. Thin, light, and extraordinarily powerful.', shortDescription: 'M2 chip, 12.9" Liquid Retina XDR, 8GB RAM, 256GB, Wi-Fi 6E', price: 109900, originalPrice: 124900, images: [{ url: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500', alt: 'iPad Pro M2' }], category: 'Tablets', subcategory: 'Premium Tablets', brand: 'Apple', stock: 20, sku: 'APPLE-IPADPRO12-M2-256', specifications: [{ key: 'Chip', value: 'Apple M2' }, { key: 'Display', value: '12.9" Liquid Retina XDR' }, { key: 'RAM', value: '8GB' }, { key: 'Storage', value: '256GB' }], tags: ['apple', 'ipad', 'tablet', 'm2', 'pro', 'creative'], ratings: 4.9, numReviews: 298, isFeatured: true, purchaseCount: 1560 },
  { name: 'Samsung Galaxy Tab S9 FE', description: 'Galaxy Tab S9 FE with 10.9" LCD display, IP68 water resistance, and S Pen included. Great productivity tablet for daily use.', shortDescription: 'Exynos 1380, 6GB RAM, 128GB, 10.9" LCD, S Pen included, IP68', price: 34999, originalPrice: 44999, images: [{ url: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=500', alt: 'Samsung Tab S9 FE' }], category: 'Tablets', subcategory: 'Android Tablets', brand: 'Samsung', stock: 40, sku: 'SAM-TABS9FE-6-128', specifications: [{ key: 'Processor', value: 'Exynos 1380' }, { key: 'Display', value: '10.9" LCD' }, { key: 'RAM', value: '6GB' }, { key: 'Storage', value: '128GB' }, { key: 'S Pen', value: 'Included' }], tags: ['samsung', 'galaxy-tab', 'android', 'tablet', 's-pen', 'productivity'], ratings: 4.4, numReviews: 567, purchaseCount: 2800 },

  // Smartwatches
  { name: 'Apple Watch Series 9', description: 'The most advanced Apple Watch with the new S9 chip, brighter Always-On Retina display, and new double tap gesture. Advanced health features including ECG and blood oxygen.', shortDescription: 'S9 chip, Always-On Display, ECG, Blood Oxygen, Double Tap', price: 41900, originalPrice: 49900, images: [{ url: 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=500', alt: 'Apple Watch Series 9' }], category: 'Smartwatches', subcategory: 'Premium', brand: 'Apple', stock: 35, sku: 'APPLE-AW9-41-MID', specifications: [{ key: 'Chip', value: 'Apple S9' }, { key: 'Display', value: '45mm Always-On Retina' }, { key: 'Health', value: 'ECG, Blood Oxygen, Temp' }, { key: 'Battery', value: '18 hours' }], tags: ['apple', 'watch', 'smartwatch', 'health', 'fitness', 'ios'], ratings: 4.8, numReviews: 543, isFeatured: true, purchaseCount: 2300 },
  { name: 'Samsung Galaxy Watch 6 Classic', description: 'Premium smartwatch with rotating bezel, comprehensive health tracking, and up to 40 hours battery. Works great with any Android phone.', shortDescription: 'Exynos W930, 47mm, Rotating Bezel, BioActive Sensor, 40hr battery', price: 32999, originalPrice: 39999, images: [{ url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500', alt: 'Galaxy Watch 6 Classic' }], category: 'Smartwatches', subcategory: 'Premium', brand: 'Samsung', stock: 28, sku: 'SAM-GW6C-47-SLV', specifications: [{ key: 'Processor', value: 'Exynos W930' }, { key: 'Display', value: '47mm Super AMOLED' }, { key: 'Battery', value: '40 hours' }], tags: ['samsung', 'watch', 'smartwatch', 'android', 'fitness', 'rotating-bezel'], ratings: 4.5, numReviews: 378, purchaseCount: 1650 },

  // Accessories & Peripherals
  { name: 'Logitech MX Master 3S', description: 'The ultimate productivity mouse with ultra-fast MagSpeed scrolling, precise 8000 DPI tracking on any surface, and quiet clicks. Perfect for creative professionals.', shortDescription: '8000 DPI MagSpeed scroll, quiet clicks, USB-C, Bluetooth & USB', price: 9295, originalPrice: 10995, images: [{ url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500', alt: 'Logitech MX Master 3S' }], category: 'Computer Peripherals', subcategory: 'Mouse', brand: 'Logitech', stock: 90, sku: 'LOGI-MXM3S-GRY', specifications: [{ key: 'DPI', value: '200-8000' }, { key: 'Battery', value: '70 days' }, { key: 'Connectivity', value: 'Bluetooth + Logi Bolt' }], tags: ['logitech', 'mouse', 'productivity', 'wireless', 'ergonomic', 'mx'], ratings: 4.7, numReviews: 1456, purchaseCount: 6700 },
  { name: 'Samsung 970 EVO Plus 1TB NVMe SSD', description: 'Blazing fast NVMe SSD with read speeds up to 3500 MB/s. Enhanced reliability with Samsung V-NAND and ideal for gaming and creative work.', shortDescription: '1TB PCIe NVMe M.2, 3500/3300 MB/s R/W, V-NAND, 5yr warranty', price: 8999, originalPrice: 12999, images: [{ url: 'https://images.unsplash.com/photo-1597852074816-d933c7d2b988?w=500', alt: 'Samsung 970 EVO Plus SSD' }], category: 'Storage', subcategory: 'SSD', brand: 'Samsung', stock: 150, sku: 'SAM-970EVOP-1TB', specifications: [{ key: 'Capacity', value: '1TB' }, { key: 'Interface', value: 'PCIe Gen 3.0 NVMe' }, { key: 'Read Speed', value: '3500 MB/s' }, { key: 'Write Speed', value: '3300 MB/s' }], tags: ['samsung', 'ssd', 'nvme', 'storage', 'm2', 'fast'], ratings: 4.8, numReviews: 3200, purchaseCount: 15000 },

  // Home Appliances
  { name: 'Dyson V15 Detect Cordless Vacuum', description: 'The most powerful cordless vacuum with built-in laser that reveals invisible dust on hard floors. LCD screen displaying real-time particle count.', shortDescription: 'Laser dust detection, 60min runtime, LCD screen, HEPA filter', price: 52900, originalPrice: 62900, images: [{ url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500', alt: 'Dyson V15' }], category: 'Home Appliances', subcategory: 'Vacuum Cleaners', brand: 'Dyson', stock: 20, sku: 'DYSON-V15-DET', specifications: [{ key: 'Suction', value: '230 AW' }, { key: 'Battery', value: '60 min max' }, { key: 'Filter', value: 'Advanced HEPA' }], tags: ['dyson', 'vacuum', 'cordless', 'home', 'cleaning', 'smart'], ratings: 4.7, numReviews: 234, purchaseCount: 890 },

  // Gaming
  { name: 'PlayStation 5 Console', description: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D audio.', shortDescription: 'PS5, Disc Edition, 825GB SSD, 4K 120fps, Ray Tracing, DualSense', price: 54990, originalPrice: 59990, images: [{ url: 'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=500', alt: 'PlayStation 5' }], category: 'Gaming', subcategory: 'Consoles', brand: 'Sony', stock: 10, sku: 'SONY-PS5-DISC', specifications: [{ key: 'Storage', value: '825GB SSD' }, { key: 'Resolution', value: 'Up to 8K, 4K 120fps' }, { key: 'Backwards Compatible', value: 'PS4 games' }, { key: 'Controller', value: 'DualSense wireless' }], tags: ['sony', 'playstation', 'ps5', 'gaming', 'console', 'next-gen'], ratings: 4.9, numReviews: 2100, isFeatured: true, purchaseCount: 7800 },
  { name: 'Razer BlackShark V2 Gaming Headset', description: 'Esports-grade headset with THX 7.1 surround sound, Razer HyperClear Cardioid Mic, and memory foam ear cushions for extended gaming sessions.', shortDescription: 'THX 7.1 Spatial Audio, HyperClear Mic, 250g, TriForce Titanium 50mm', price: 4999, originalPrice: 7999, images: [{ url: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=500', alt: 'Razer BlackShark V2' }], category: 'Gaming', subcategory: 'Headsets', brand: 'Razer', stock: 55, sku: 'RAZER-BSV2-BLK', specifications: [{ key: 'Drivers', value: '50mm TriForce Titanium' }, { key: 'Sound', value: 'THX 7.1 Surround' }, { key: 'Mic', value: 'HyperClear Cardioid' }, { key: 'Connection', value: '3.5mm + USB Sound Card' }], tags: ['razer', 'headset', 'gaming', 'esports', 'surround-sound', 'mic'], ratings: 4.5, numReviews: 1890, purchaseCount: 8900 },
];

async function seed() {
  try {
    await connectDB();
    console.log('🌱 Starting database seed...');

    // Clear existing
    await Product.deleteMany({});
    await User.deleteMany({});
    console.log('🗑️  Cleared existing data');

    // Create admin user
    const admin = await User.create({
      name: 'Admin User',
      email: 'admin@shopai.com',
      password: 'Admin@123',
      role: 'admin',
    });
    console.log(`✅ Admin created: admin@shopai.com / Admin@123`);

    // Create test user
    const user = await User.create({
      name: 'Test User',
      email: 'user@shopai.com',
      password: 'User@123',
      role: 'user',
    });
    console.log(`✅ Test user created: user@shopai.com / User@123`);

    // Seed products
    await Product.insertMany(products);
    console.log(`✅ ${products.length} products seeded`);

    console.log('\n🎉 Seed complete!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed error:', error);
    process.exit(1);
  }
}

seed();
